let productos = [
  {
    id: 1,
    marca: "LG",
    precioRenta: 142.37,
    modelo: "Lavasecadora electrónica 12 kg WD12VVC4S6S",
    dispensadorAutomatico: "Jabón",
    luzInterior: "No",
    ajustesTemperatura: 6,
    seguroNinos: "Sí",
    sostenible: "Ahorro de agua",
    tipoCarga: "Carga frontal",
  },
  {
    id: 2,
    marca: "SAMSUNG",
    precioRenta: 95.8,
    modelo: "Lavadora 20 kg automática carga superior WA20A3341GW/AX",
    carga: "Superior",
    filtroAtrapaPelusa: "No",
    ajustesTemperatura: 4,
    tipoLavadora: "Automática",
    tecnologiaInverter: "No",
  },
  {
    id: 3,
    marca: "HISENSE",
    precioRenta: 160.1,
    modelo: "Lavasecadora eléctrica 16 kg 10 kg WD5S1645BT",
    filtroAtrapaPelusa: "Sí",
    ajustesTemperatura: 5,
    seguroNinos: "Sí",
    tecnologiaInverter: "Sí",
    tipoCarga: "Carga frontal",
  },
  {
    id: 4,
    marca: "KOBLENZ",
    precioRenta: 87.45,
    modelo: "Lavadora 19 kg automática carga superior lwm-19iir Frankfurt",
    carga: "Superior",
    filtroAtrapaPelusa: "Sí",
    ajustesTemperatura: 3,
    tipoLavadora: "Automática",
    tecnologiaInverter: "No",
  },
  {
    id: 5,
    marca: "LG",
    precioRenta: 73.9,
    modelo:
      "Lavadora doble tina 18 KG semiautomática doble carga WP18MAR.DBMELAT",
    carga: "Doble carga",
    filtroAtrapaPelusa: "No",
    ajustesTemperatura: 1,
    tipoPanelControl: "Perillas",
  },
  {
    id: 6,
    marca: "SAMSUNG",
    precioRenta: 189.99,
    modelo: "Lavasecadora electrónico 12.5 kg WD12TP04DBE/AX",
    dispensadorAutomatico: "No tiene",
    luzInterior: "No",
    ajustesTemperatura: 5,
    seguroNinos: "Sí",
    tecnologiaInverter: "Sí",
    tipoCarga: "Carga frontal",
  },
  {
    id: 7,
    marca: "MABE",
    precioRenta: 112.75,
    modelo: "Lavadora 22 kg automática carga superior LMA72215WBAB1",
    carga: "Superior",
    filtroAtrapaPelusa: "No",
    ajustesTemperatura: 6,
    tipoLavadora: "Automática",
    sostenible: "Ahorro de agua",
  },
  {
    id: 8,
    marca: "HISENSE",
    precioRenta: 69.5,
    modelo: "Lavadora doble tina 18 kg manual doble carga WSA1803P",
    carga: "Doble carga",
    filtroAtrapaPelusa: "Sí",
    ajustesTemperatura: 1,
    tipoPanelControl: "Perillas",
  },
  {
    id: 9,
    marca: "WHIRLPOOL",
    precioRenta: 153.6,
    modelo: "Lavadora 22 kg automática carga superior 8MWTWLA31WJG",
    carga: "Superior",
    filtroAtrapaPelusa: "No",
    ajustesTemperatura: 4,
    tipoLavadora: "Automática",
  },
  {
    id: 10,
    marca: "MABE",
    precioRenta: 130.0,
    modelo: "Lavadora 22 kg automática carga superior Lmh72211wbab0",
    carga: "Superior",
    filtroAtrapaPelusa: "No",
    ajustesTemperatura: 6,
    tipoPanelControl: "Digital, botones y perillas",
    tecnologiaInverter: "No",
  },
];


localStorage.setItem("productos", JSON.stringify(productos));